import java.util.Map;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author tkaaya
 */
public class Login extends javax.swing.JFrame {

    UserLogin loginInfo;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        loginInfo = new UserLogin();
        try {
            loginInfo.loadFromFile("users.dat");
        } catch (Exception e) {
            // If loading fails, start with empty user list
            loginInfo.setUserList(new HashMap<>());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // Removed unnecessary @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtUserId = new javax.swing.JTextField();
        jbtnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jcboRole = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jlblPass = new javax.swing.JLabel();
        jtxtPassword = new javax.swing.JTextField();
        jbtnForgotPassword = new javax.swing.JButton();
        jbtnRegister = new javax.swing.JButton();
        jbtnProfile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("User ID");

        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        jLabel3.setText("Login As");

        jcboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Professor" }));
        jcboRole.setSelectedIndex(1);

        jbtnForgotPassword.setText("Forgot Password");
        jbtnForgotPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnForgotPasswordActionPerformed(evt);
            }
        });

        jbtnRegister.setText("Register");
        jbtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegisterActionPerformed(evt);
            }
        });

        jbtnProfile.setText("Profile");
        jbtnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jlblPass.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblPass)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcboRole, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnForgotPassword)
                    .addComponent(jbtnLogin)
                    .addComponent(jbtnRegister)
                    .addComponent(jbtnProfile))
                .addGap(88, 88, 88))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jcboRole, jtxtPassword, jtxtUserId});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPass)
                    .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnForgotPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnProfile)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jcboRole, jtxtPassword, jtxtUserId});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        boolean isFound = false; // Fixed typo in variable name
        for (Map.Entry<String, User> entry : loginInfo.getUserList().entrySet()) {
            User currentUser = entry.getValue();
            if (!isFound && jtxtUserId.getText().equalsIgnoreCase(entry.getKey())
                    && jtxtPassword.getText().equals(currentUser.getPassword()) // Fixed typo
                    && jcboRole.getSelectedIndex() == currentUser.getRole()) {
                if (jcboRole.getSelectedIndex() == 0) { // Student
                    ClassRegistration registor = new ClassRegistration(currentUser);
                    registor.setVisible(true);
                } else { // Professor
                    UMS ums = new UMS(loginInfo);
                    ums.setVisible(true);
                }
                isFound = true;
            }
        }
        if (!isFound) {
            JOptionPane.showMessageDialog(null, "User does not exist. Try again!", "Invalid Data", JOptionPane.ERROR_MESSAGE);
        }
        reset();
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jbtnForgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {
        String userId = JOptionPane.showInputDialog(this, "Enter your User ID:", "Forgot Password", JOptionPane.QUESTION_MESSAGE);
        if (userId == null || userId.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "User ID cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        User user = loginInfo.getUserList().get(userId);
        if (user != null) {
            String newPassword = JOptionPane.showInputDialog(this, "Enter a new password:", "Reset Password", JOptionPane.QUESTION_MESSAGE);
            if (newPassword != null && !newPassword.trim().isEmpty()) {
                user.setPassword(newPassword);
                JOptionPane.showMessageDialog(this, "Password reset successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Password cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "User not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jbtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {
        String id = JOptionPane.showInputDialog(this, "Enter new User ID:");
        String name = JOptionPane.showInputDialog(this, "Enter your Name:");
        String password = JOptionPane.showInputDialog(this, "Enter Password:");
        String email = JOptionPane.showInputDialog(this, "Enter Email:");
        int role = JOptionPane.showConfirmDialog(this, "Are you a Professor?", "Role", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION ? 1 : 0;
        if (id != null && !id.trim().isEmpty() && !loginInfo.userExists(id)) {
            User newUser = new User(id, name, password, role, email, "");
            loginInfo.addUser(newUser);
            JOptionPane.showMessageDialog(this, "Registration successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
            try { loginInfo.saveToFile("users.dat"); } catch (Exception ex) {}
        } else {
            JOptionPane.showMessageDialog(this, "User ID exists or invalid!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jbtnProfileActionPerformed(java.awt.event.ActionEvent evt) {
        String id = jtxtUserId.getText();
        User user = loginInfo.getUserList().get(id);
        if (user != null) {
            JOptionPane.showMessageDialog(this, "Name: " + user.getName() + "\nEmail: " + user.getEmail() + "\nBio: " + user.getProfileBio(), "Profile", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "User not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void reset() {
        jtxtUserId.setText("");
        jtxtPassword.setText("");
        jcboRole.setSelectedIndex(1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Login loginFrame = new Login();
                loginFrame.setVisible(true);

                Runtime.getRuntime().addShutdownHook(new Thread(() -> {
                    try {
                        loginFrame.loginInfo.saveToFile("users.dat");
                    } catch (Exception e) {}
                }));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnForgotPassword;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnProfile;
    private javax.swing.JButton jbtnRegister;
    private javax.swing.JComboBox<String> jcboRole;
    private javax.swing.JLabel jlblPass;
    private javax.swing.JTextField jtxtPassword;
    private javax.swing.JTextField jtxtUserId;
    // End of variables declaration//GEN-END:variables
}
